project:
  type: book

execute:
  freeze: auto

book:
  title: "Inha_Accident_Report"
  author: "Jaeseong Choe"
  date: 2023/03/19
  downloads: [pdf]
  repo-url: https://github.com/sorrychoe/inha_accident
  repo-actions: edit
  search: true
  reader-mode: true
  sidebar:
    style: "docked"
  chapters:
    - index.qmd
    - part: "Reports"
      chapters:
        - inha_clustering.qmd
        - inha_network.qmd


format:
  bookup-html


